branches:
  only:
    - master

language: node_js

services:
  - mongodb

node_js:
  - "0.11"

before_script:
  - "npm install -g gulp"
  - "npm install -g bower"
  - "npm install"
  - "bower install"

script:
  - "npm run ci"

notifications:
  email:
    - ram@hiddentao.com

